name: Tests

on:
  push:
    paths:
      - 'inc/**'
      - 'tests/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'inc/**'
      - 'tests/**'
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd tests && make
